from edit_operations.base_edit_operation import BaseEditOperation, IndependentTextonEditOperation
from edit_operations.add_shadow import AddShadow
from edit_operations.density_map_removal import DensityMapRemoval
from edit_operations.forced_anisotropy import ForcedAnisotropy
from edit_operations.probability_removal import ProbabilityRemoval
from edit_operations.probability_tint import ProbabilityTint
from edit_operations.small_texton_removal import SmallTextonRemoval
from edit_operations.texton_replacement import TextonReplacement
from edit_operations.flatten import Flatten
