from segmentation.base_segmentation import BaseSegmentation
from segmentation.flood_fill_segmentation import FloodFillSegmentation
from segmentation.irregular_patch_segmentation import IrregularPatchSegmentation
from segmentation.regular_patch_segmentation import RegularPatchSegmentation
from segmentation.slic_segmentation import SLICSegmentation
from segmentation.felzenszwalb_segmentation import FelzenszwalbSegmentation
from segmentation.sam_segmentation import SAMSegmentation
